Feat: add err info to issue
freeCodeCamp-China/article-webpage-to-markdown-action pull request #18
Opened 2022-05-25 03:00 UTC by luojiyin1987

Checklist（清单）:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org)（我已经阅读 [freeCodeCamp 贡献指南](https://contribute.freecodecamp.org)）.
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)（我的 pull request 有一个详细的标题，而不是像“添加 index.md 文件这样的粗略标题”。）
- [ ] My pull request targets the `main` branch of this repo.（我的 pull rewuest 基于本仓库 `main` 分支修改。）

Closes #17 

当action 运行失败时，添加信息到  issue ，方便人发现问题。

2022-05-25 03:07 UTC, luojiyin1987 commented
1  是否可以从  context 中 获取 githu_token ,  这样，不用在 workflows,维护一个    `secrets.GITHUB_TOKEN`  变量。

 2   对    @actions/github    @octokit  两个包还是不太了解。 现在是通过  `github.context` 的方法获取 `owner` , `repo`, 信息，是否有更好的办法， 减少包的引用。

2022-05-25 15:02 UTC, luojiyin1987 commented
函数 `addComment`  函数对应的测试， 我在看  `Octokit` 他们的测试用例。

2022-05-25 16:24 UTC, TechQuery requested changes

2022-05-25 16:24 UTC, TechQuery commented on src/utilities.js
> +  }
前面条件取反，就可以提前 `throw`，主体逻辑即可少一层缩进。

2022-05-25 16:24 UTC, TechQuery commented on src/utilities.js
> +  const githubToken = core.getInput("githubToken") || undefined;
方法无法取到值时，其返回值就是一个假值，无需再写一个 `undefined`

2022-05-26 07:07 UTC, TechQuery approved these changes

2022-05-26 14:22 UTC, luojiyin1987 commented
[文档](https://github.com/actions/toolkit/blob/main/docs/github-package.md)
```js
const nock = require('nock');
const path = require('path');

describe('action test suite', () => {
  it('It posts a comment on an opened issue', async () => {
    const welcomeMessage = 'hello';
    const repoToken = 'token';
    process.env['INPUT_WELCOME-MESSAGE'] = welcomeMessage;
    process.env['INPUT_REPO-TOKEN'] = repoToken;

    process.env['GITHUB_REPOSITORY'] = 'foo/bar';
    process.env['GITHUB_EVENT_PATH'] = path.join(__dirname, 'payload.json');

    // TODO
  });
});
```

对方也没补上测试。   :cold_sweat:

2022-05-27 02:35 UTC, luojiyin1987 commented
在查看 [octokit.js 官方的有关 `createComment`  测试代码](https://github.com/octokit/octokit.js/blob/main/test/app.test.ts)
我倾向不写 `addComment` 函数的测试代码。   不想为一个不是核心的功能，引入大量的依赖。

2022-05-28 05:33 UTC, stevending1st approved these changes

2022-05-28 05:52 UTC, stevending1st commented
LGTM
@TechQuery

2022-05-28 12:16 UTC, merged