remove AD script  of  freeCodeCamp
freeCodeCamp-China/article-webpage-to-markdown-action pull request #20
Opened 2022-09-11 14:56 UTC by luojiyin1987

Checklist（清单）:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org)（我已经阅读 [freeCodeCamp 贡献指南](https://contribute.freecodecamp.org)）.
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)（我的 pull request 有一个详细的标题，而不是像“添加 index.md 文件这样的粗略标题”。）
- [ ] My pull request targets the `main` branch of this repo.（我的 pull rewuest 基于本仓库 `main` 分支修改。）

Closes #19

2022-09-12 09:30 UTC, luojiyin1987 commented
测试代码有误， 还在修改中

2022-09-15 14:00 UTC, TechQuery requested changes

2022-09-15 14:00 UTC, TechQuery commented on src/__test__/utilities.test.js
> +  })
改写为 `async` + `await`，且此处无需 `catch`

2022-09-15 16:27 UTC, TechQuery approved these changes

2022-09-15 16:28 UTC, merged