fix: authorInfo two blank line
freeCodeCamp-China/article-webpage-to-markdown-action pull request #3
Opened 2022-03-25 03:37 UTC by luojiyin1987

Checklist（清单）:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org)（我已经阅读 [freeCodeCamp 贡献指南](https://contribute.freecodecamp.org)）.
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)（我的 pull request 有一个详细的标题，而不是像“添加 index.md 文件这样的粗略标题”。）
- [ ] My pull request targets the `main` branch of this repo.（我的 pull rewuest 基于本仓库 `main` 分支修改。）

Closes #XXXXX

修复 生成作者信息出现两行空白行

2022-03-25 03:37 UTC, luojiyin1987 commented
#2

2022-03-25 03:41 UTC, stevending1st approved these changes

2022-03-25 03:41 UTC, merged

2022-05-15 06:56 UTC, TechQuery requested changes

2022-05-15 06:56 UTC, TechQuery commented on src/utilities.js
> +    const authorName = authorCardName.text().replace(/[\n ]/g, '');
会用正则表达式非常好，但清理前后空白符还有更简单的方法
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/Trim