yaml
freeCodeCamp-China/article-webpage-to-markdown-action pull request #30
Opened 2024-07-26 11:47 UTC by douxiaobo

Checklist（清单）:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org)（我已经阅读 [freeCodeCamp 贡献指南](https://contribute.freecodecamp.org)）.
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)（我的 pull request 有一个详细的标题，而不是像“添加 index.md 文件这样的粗略标题”。）
- [ ] My pull request targets the `main` branch of this repo.（我的 pull rewuest 基于本仓库 `main` 分支修改。）

Closes #XXXXX

2024-07-26 12:48 UTC, TechQuery requested changes

2024-07-26 12:48 UTC, TechQuery commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +assignees: []
```suggestion
labels:
  - bug
assignees:
  - TechQuery
```
1. YAML 的列表和键值对相当于编程语言当中的数组和对象，不可能在同一级同时存在数组和字符串索引，所以两级一定有缩进。

2. YAML 没有特殊符号的字符串可以不用加引号。

3. issue 的指派人可设为仓库排名靠前的贡献者。

2024-07-26 12:48 UTC, TechQuery commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +  Add any other context about the problem here.（添加其他你想添加的内容）
我们之所以用 YAML 格式的 issue form 配置文件，就是为了把问题细项拆分为独立的各类输入框，而不要这种大段的描述文本。

issue 参考任务里有可视化工具可直接生成不同的表单项。

2024-07-26 12:54 UTC, TechQuery commented
1. 不同文件中的同类问题请自行修改。

2. PR description 正文中的 checklist 所述内容需要一一阅读并确认已按照所示要求完成，最后在完成项上打勾。同时要将最后的 `Closes #xxx` 中的 `xxx` 替换为你要解决的具体 issue 号码。

2024-07-26 13:41 UTC, douxiaobo commented
> 1. 不同文件中的同类问题请自行修改。
> 2. PR description 正文中的 checklist 所述内容需要一一阅读并确认已按照所示要求完成，最后在完成项上打勾。同时要将最后的 `Closes #xxx` 中的 `xxx` 替换为你要解决的具体 issue 号码。

我已经做好了。不知道是否可以了。

2024-07-26 14:12 UTC, TechQuery requested changes

2024-07-26 14:12 UTC, TechQuery commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +     description: '用简单的语言描述 bug。'
```suggestion
  - type: textarea
    id: bug-description
    attributes:
      label: 'Describe the bug（bug 描述）'
      description: 'A clear and concise description of what the bug is.（用简单的语言描述 bug。）
      required: true
```
（下同）

2024-07-26 14:12 UTC, TechQuery commented on .github/ISSUE_TEMPLATE/bug-report.yml
> + - TechQuery
```suggestion
labels:
  - bug
assignees: 
  - TechQuery
```
缩进的空格通常是双数。

2024-07-26 14:12 UTC, TechQuery commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +   id: has-screenshots
```suggestion
 - type: textarea
   id: screenshots
```
GitHub issue 只有富文本编辑框可以上传图片。

2024-07-26 14:13 UTC, TechQuery commented
> 我的 pull request 有一个详细的标题，而不是像“添加 index.md 文件这样的粗略标题”。

@douxiaobo

2024-07-27 10:53 UTC, TechQuery requested changes

2024-07-27 10:53 UTC, TechQuery commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      required: true
```suggestion
  - type: textarea
    id: screenshots
    attributes:
      label: 'Screenshots（截图）'
      placeholder: 'If applicable, add screenshots to help explain your problem.（可以截图辅助描述。）'
```

2024-07-27 10:53 UTC, TechQuery commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +        Node.js’s Version（Node.js 版本）: [e.g. 12.12.12（例如：12.12.12）]
```suggestion
        - OS（操作系统）: [e.g. iOS（例如：iOS）]
        - Node.js’s Version（Node.js 版本）: [e.g. 12.12.12（例如：12.12.12）]
```
提示用户用列表格式书写。

2024-07-27 10:53 UTC, TechQuery commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      required: true
```suggestion
  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context（其他）'
      placeholder: 'Add any other context about the problem here.（添加其他你想添加的内容）'
```
根据描述可知：这一项不是必须的。

2024-07-27 10:53 UTC, TechQuery commented on .github/ISSUE_TEMPLATE/feature.yml
> +      required: true
```suggestion
  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context（其他）'
      placeholder: 'Add any other context about the problem here.（添加其他你想添加的内容）'
```

2024-07-27 14:59 UTC, TechQuery approved these changes

2024-07-28 05:52 UTC, merged