feat: Add 3 new features to adapt to the subsequent call chain.
freeCodeCamp-China/article-webpage-to-markdown-action pull request #31
Opened 2024-07-30 09:23 UTC by budblack

Checklist（清单）:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org)（我已经阅读 [freeCodeCamp 贡献指南](https://contribute.freecodecamp.org)）.
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)（我的 pull request 有一个详细的标题，而不是像“添加 index.md 文件这样的粗略标题”。）
- [  ] My pull request targets the `main` branch of this repo.（我的 pull rewuest 基于本仓库 `main` 分支修改。）

Added the includeSelector parameter to define the effective content area during the webpage fetching process.
Added the skipSameArticleCheck parameter to mark skipping the duplicate file detection during the article crawling process.
Added the skipIssueComment parameter to mark skipping the issue comment output after the article crawling is completed.

2024-07-30 17:24 UTC, TechQuery requested changes

2024-07-30 17:24 UTC, TechQuery commented on action.yml
> +    default: 'false'
为何要跳过同名文件检查？这个爬虫是直接推到主分支的，不查重就会覆盖已翻译的文章。

2024-07-30 17:24 UTC, TechQuery commented on action.yml
> +    default: 'false'
1. 之前我们电话讨论过的自动翻译流程是：直接创建 PR 并关联 issue，不需要再发 comment，现有 comment 不影响新增步骤
2. 我打算把 comment 中的关键数据设为本 action 的  `outputs`，让内置 CLI 在后面的步骤发 comment：https://docs.github.com/en/actions/managing-issues-and-pull-requests/commenting-on-an-issue-when-a-label-is-added

2024-07-30 17:24 UTC, TechQuery commented on src/index.ts
> +  }
不明白为何这么做，后面的工具函数已按 HTML 语义化做了正文抽取：
https://github.com/budblack/article-webpage-to-markdown-action/blob/ea8fd4a96a7896ab553183f15b82f2907c0bc896/src/utilities.ts#L146-L147

2024-07-31 09:39 UTC, budblack commented on action.yml
> +    default: 'false'
逻辑不一样，新仓库采用额外路径存储已翻译文章，原始文件跳过同名检查以刷新仓库文件。

2024-07-31 09:40 UTC, budblack commented on src/index.ts
> +  }
原有逻辑把作者头像抽出来了，新增 includeSelector 便于手动组装需要抽取的选择器清单

2024-07-31 09:42 UTC, budblack commented on action.yml
> +    default: 'false'
现有 comment 内容不完整，如果不跳过的话后续也得 update 它。

2024-07-31 09:49 UTC, budblack commented
要不我单开一个分支用于维护多语言翻译仓库使用的文章爬虫 action，或者使用我的 fork 版本。
我感觉非要强行统一到这个版本上太别扭了。
这一周以来我改了好几个版本，基本都是为了保留对这个 action 的直接引用，不得不在后续 action 中实现兼容逻辑。
我感觉这样把简单事情复杂化了。

2024-07-31 09:56 UTC, budblack commented on src/index.ts
> +  }
建议增加选择器，通过参数配置抽取范围 document.querySelectorAll('span.author-card-name,section.post-full-content')

2024-07-31 11:05 UTC, TechQuery commented on action.yml
> +    default: 'false'
> 逻辑不一样，新仓库采用额外路径存储已翻译文章，原始文件跳过同名检查以刷新仓库文件。

```shell
mv original.md zh-CN/original.md
```
可解决

2024-07-31 11:06 UTC, TechQuery commented on action.yml
> +    default: 'false'
> 现有 comment 内容不完整，如果不跳过的话后续也得 update 它。

即将合并的新版 #32 已不做 comment，由用户拿到输出信息自行决定。

2024-07-31 11:11 UTC, TechQuery commented on src/index.ts
> +  }
> 建议增加选择器，通过参数配置抽取范围 document.querySelectorAll('span.author-card-name,section.post-full-content')

1. 我会再增加 `post` 这个选择符关键字。
2. 如果要增强完全自定义的选择符，则需要跳过原有的猜测逻辑，而不是再加一步。

2024-07-31 11:18 UTC, TechQuery commented
> 要不我单开一个分支用于维护多语言翻译仓库使用的文章爬虫 action，或者使用我的 fork 版本。
> 我感觉非要强行统一到这个版本上太别扭了。
> 这一周以来我改了好几个版本，基本都是为了保留对这个 action 的直接引用，不得不在后续 action 中实现兼容逻辑。
> 我感觉这样把简单事情复杂化了。

你没有理解 GitHub actions 的设计理念：

不是一个流程把所有的事情都做完，或者上游一定要跟着你下游的新需求来改。

而是上游尽最大可能只做好它那一环的事，并且输出必要的数据，让后面的步骤能很好地穿起来。

以此来术业专攻地把整个流程做好，提高长远的维护效率，而不是一时的开发效率。

否则你根本不需要用 `use: xxx/yyy@zzz` 的 GitHub actions，直接用 Web hook 接 Jenkins 等其它传统 CI/CD 就行了。

2024-07-31 13:58 UTC, luojiyin1987 commented on action.yml
> +    default: 'false'
爬取的原始内容存在哪里？   直接存在 action 的内存中？

2024-12-13 15:34 UTC, closed without merging